# Generated by Django 2.2 on 2020-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio', '0002_auto_20200701_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(),
        ),
    ]
